# Generated by Django 3.2.13 on 2022-07-03 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Visio_Website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='application_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applications',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(help_text='Upload picture of size 1920x850', max_length=2000),
        ),
    ]
