# Generated by Django 3.2.13 on 2022-07-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visio_Website', '0002_auto_20220703_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whyus',
            name='picture',
            field=models.ImageField(help_text='Upload image of size 650x450', upload_to='images/team'),
        ),
    ]
