# Generated by Django 3.2.13 on 2022-07-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visio_Website', '0003_alter_whyus_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='applications',
            options={'verbose_name': 'Applications', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Solutions', 'verbose_name_plural': 'Solutions'},
        ),
        migrations.AddField(
            model_name='supportingcontent',
            name='blog_banner',
            field=models.ImageField(blank=True, help_text='Upload picture of size 1920x280', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='supportingcontent',
            name='case_study_banner',
            field=models.ImageField(blank=True, help_text='Upload picture of size 1920x280', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='supportingcontent',
            name='products_banner',
            field=models.ImageField(blank=True, help_text='Upload picture of size 1920x280', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload image of size 140x130', null=True, upload_to='images/clients'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(help_text='Upload picture of size 1920x850', upload_to='images/slider'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=2000),
        ),
    ]
